Repository 100-hours-a-week/6-nemo-be, pull requests merged in 2025-06, with the labels that each got.

#146 hotfix: 일정 참석 거절 시 처리 안 되는 오류 해결 (#145)
  src/main/java/kr/ai/nemo/domain/schedule/validator/ScheduleValidator.java
  src/main/java/kr/ai/nemo/domain/scheduleparticipants/service/ScheduleParticipantsService.java
Labels: 버그-심각

#155 모임 추천 AI 챗봇 서비스 구현
  build.gradle.kts
  src/main/java/kr/ai/nemo/domain/group/controller/v1/GroupController.java
  src/main/java/kr/ai/nemo/domain/group/controller/v2/GroupController.java
  src/main/java/kr/ai/nemo/domain/group/dto/request/GroupAiDeleteRequest.java
  src/main/java/kr/ai/nemo/domain/group/dto/request/GroupAiQuestionRecommendRequest.java
  src/main/java/kr/ai/nemo/domain/group/dto/request/GroupAiQuestionRequest.java
  src/main/java/kr/ai/nemo/domain/group/dto/request/GroupChatbotQuestionRequest.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupChatbotQuestionResponse.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupChatbotSessionResponse.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupRecommendResponse.java
  src/main/java/kr/ai/nemo/domain/group/exception/GroupErrorCode.java
  src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java
  src/main/java/kr/ai/nemo/domain/group/service/AiGroupGenerateClient.java
  src/main/java/kr/ai/nemo/domain/group/service/AiGroupService.java
  src/main/java/kr/ai/nemo/domain/group/service/GroupCommandService.java
  src/main/java/kr/ai/nemo/domain/group/service/GroupGenerateService.java
  src/main/java/kr/ai/nemo/domain/group/service/GroupQueryService.java
  src/main/java/kr/ai/nemo/domain/group/validator/GroupValidator.java
  src/main/java/kr/ai/nemo/domain/groupparticipants/controller/v1/GroupParticipantsController.java
  src/main/java/kr/ai/nemo/domain/groupparticipants/controller/v2/GroupParticipantsController.java
  src/main/java/kr/ai/nemo/domain/groupparticipants/dto/request/GroupParticipantAiRequest.java
  src/main/java/kr/ai/nemo/domain/schedule/service/ScheduleCommandService.java
  src/main/java/kr/ai/nemo/global/common/constants/CookieConstants.java
  src/main/java/kr/ai/nemo/global/config/AiApiProperties.java
  src/main/java/kr/ai/nemo/global/config/AppConfig.java
  src/main/java/kr/ai/nemo/global/config/RedisConfig.java
  src/main/java/kr/ai/nemo/global/redis/CacheKeyUtil.java
  src/main/java/kr/ai/nemo/global/redis/RedisCacheService.java
  src/main/resources/application.yml
Labels: 기능 구현

#159 모임 챗봇 API 개발 (#144)
  .github/workflows/v2-prod-cicd.yaml
  build.gradle.kts
  dump.rdb
  src/main/java/kr/ai/nemo/NemoApplication.java
  src/main/java/kr/ai/nemo/domain/group/controller/v2/GroupController.java
  src/main/java/kr/ai/nemo/domain/group/domain/enums/ChatbotRole.java
  src/main/java/kr/ai/nemo/domain/group/dto/request/ChatMessage.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupAiRecommendResponse.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupChatbotQuestionResponse.java
  src/main/java/kr/ai/nemo/domain/group/dto/response/GroupChatbotSessionResponse.java
  src/main/java/kr/ai/nemo/domain/group/repository/GroupRepository.java
  src/main/java/kr/ai/nemo/domain/group/service/AiGroupService.java
  src/main/java/kr/ai/nemo/domain/group/service/GroupCommandService.java
  src/main/java/kr/ai/nemo/domain/group/service/GroupQueryService.java
  src/main/java/kr/ai/nemo/domain/group/validator/GroupValidator.java
  src/main/java/kr/ai/nemo/global/config/AppConfig.java
  src/main/java/kr/ai/nemo/global/redis/CacheConstants.java
  src/main/java/kr/ai/nemo/global/redis/RedisCacheService.java
  src/main/resources/application.yml
Labels: 버그-일반, 기능 구현

#180 Fix: OTLP 포트 설정 오류 설정 (4317->4318)
  Dockerfile
  src/main/resources/application.yml
Labels: 기능 구현

#182 access token 발급, 인증 방식 header에서 cookie로 변경
  src/main/java/kr/ai/nemo/domain/auth/controller/AuthController.java
  src/main/java/kr/ai/nemo/domain/auth/domain/enums/Token.java
  src/main/java/kr/ai/nemo/domain/auth/dto/TokenRefreshResponse.java
  src/main/java/kr/ai/nemo/domain/auth/security/JwtAuthenticationFilter.java
  src/main/java/kr/ai/nemo/domain/auth/service/OauthService.java
  src/main/java/kr/ai/nemo/domain/auth/service/TokenManager.java
  src/main/java/kr/ai/nemo/domain/groupparticipants/validator/GroupParticipantValidator.java
  src/main/java/kr/ai/nemo/global/util/UriGenerator.java
  src/test/java/kr/ai/nemo/domain/auth/controller/AuthControllerTest.java
  src/test/java/kr/ai/nemo/domain/auth/service/OauthServiceTest.java
  src/test/java/kr/ai/nemo/domain/auth/service/TokenManagerTest.java
Labels: 기능 구현
